dependencies: (deps): bump lycheeverse/lychee-action from 2.3.0 to 2.4.0 in the actions group (#269)
Bumps the actions group with 1 update:
[lycheeverse/lychee-action](https://github.com/lycheeverse/lychee-action).

Updates `lycheeverse/lychee-action` from 2.3.0 to 2.4.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/lycheeverse/lychee-action/releases">lycheeverse/lychee-action's
releases</a>.</em></p>
<blockquote>
<h2>Version 2.4.0</h2>
<h2>What's Changed</h2>
<ul>
<li>
<p>lychee now has a new task output, which allows to track which links
got fixed more easily.
It looks like this:</p>
<p>[test.html]:</p>
<ul>
<li>[X] [404] <a
href="https://en.wikipedia.org/wiki/foo">https://en.wikipedia.org/wiki/foo</a>
| Network error: Not Found</li>
<li>[ ] [404] <a
href="https://en.wikipedia.org/wiki/bar">https://en.wikipedia.org/wiki/bar</a>
| Network error: Not Found</li>
<li>[ ] [ERROR] <a
href="https://example.com/baz">https://example.com/baz</a> | Network
error: error sending request for url (<a
href="https://example.com/baz">https://example.com/baz</a>) Maybe a
certificate error?</li>
</ul>
<p>Each broken link has a checkbox that can be ticked off once fixed.
Credit goes to <a
href="https://github.com/Arteiii"><code>@​Arteiii</code></a> for the
idea and the implementation.
See <a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/274">#274</a>
for more information.</p>
</li>
<li>
<p>Update To latest lychee Release by <a
href="https://github.com/Arteiii"><code>@​Arteiii</code></a> in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/279">lycheeverse/lychee-action#279</a></p>
</li>
<li>
<p>Add <code>workingDirectory</code> argument by <a
href="https://github.com/mre"><code>@​mre</code></a> in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/283">lycheeverse/lychee-action#283</a></p>
</li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/Arteiii"><code>@​Arteiii</code></a> made
their first contribution in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/279">lycheeverse/lychee-action#279</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/lycheeverse/lychee-action/compare/v2...v2.4.0">https://github.com/lycheeverse/lychee-action/compare/v2...v2.4.0</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/1d97d84f0bc547f7b25f4c2170d87d810dc2fb2c"><code>1d97d84</code></a>
Add <code>workingDirectory</code> argument (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/283">#283</a>)</li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/a99389aeff3c193ffb6f0741178e519569d3f404"><code>a99389a</code></a>
Update To latest Release and add Checkbox Option (fixes <a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/274">#274</a>)
(<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/279">#279</a>)</li>
<li>See full diff in <a
href="https://github.com/lycheeverse/lychee-action/compare/f613c4a64e50d792e0b31ec34bbcbba12263c6a6...1d97d84f0bc547f7b25f4c2170d87d810dc2fb2c">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=lycheeverse/lychee-action&package-manager=github_actions&previous-version=2.3.0&new-version=2.4.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Arjun Verma <arjxn.py@gmail.com>